export const softwares = [
  {
    colums: 'first-column',
    skills: [
      { image: '/images/devops-1.png', label: 'Promotheus', jobType: 'devops' },
      { image: '/images/devops-2.png', label: 'Loki', jobType: 'devops' },
      { image: '/images/devops-3.png', label: 'Bitbucket', jobType: 'devops' },
      { image: '/images/devops-4.png', label: 'Gitlab', jobType: 'devops' },
      { image: '/images/devops-5.png', label: 'ELK', jobType: 'devops' },
      { image: '/images/devops-6.png', label: 'Grafana', jobType: 'devops' },
      { image: '/images/devops-7.png', label: 'Terraform', jobType: 'devops' },
      { image: '/images/mobile-1.png', label: 'IOS', jobType: 'mobile' },
      { image: '/images/devops-8.png', label: 'Docker', jobType: 'devops' },
      { image: '/images/backend-1.png', label: 'Loki', jobType: 'backend' },
      { image: '/images/backend-2.png', label: 'Bitbucket', jobType: 'backend' },
      { image: '/images/backend-3.png', label: 'Gitlab', jobType: 'backend' },
      { image: '/images/devops-5.png', label: 'YouTrack', jobType: 'test' },
      { image: '/images/devops-6.png', label: 'Appium', jobType: 'test' },
      { image: '/images/devops-7.png', label: 'Cypress', jobType: 'test' },
      { image: '/images/mobile-1.png', label: 'Jmeter', jobType: 'test' },
    ],
  },
  {
    colums: 'second-column',
    skills: [
      { image: '/images/mobile-4.png', label: 'Kotlin', jobType: 'mobile' },
      { image: '/images/mobile-5.png', label: 'Android', jobType: 'mobile' },
      { image: '/images/mobile-6.png', label: 'Java', jobType: 'mobile' },
      { image: '/images/structure-1.png', label: 'Azure', jobType: 'infrastructure' },
      { image: '/images/mobile-2.png', label: 'Swift', jobType: 'mobile' },
      { image: '/images/mobile-3.png', label: 'Flutter', jobType: 'mobile' },
      { image: '/images/frontend-1.png', label: 'Next.JS', jobType: 'frontend' },
      { image: '/images/frontend-2.png', label: 'React.JS', jobType: 'frontend' },
      { image: '/images/backend-4.png', label: 'PHP', jobType: 'backend' },
      { image: '/images/backend-5.png', label: 'GO', jobType: 'backend' },
      { image: '/images/frontend-4.png', label: 'Ant Design', jobType: 'frontend' },
      { image: '/images/frontend-5.png', label: 'Gatsby.JS', jobType: 'frontend' },
      { image: '/images/backend-7.png', label: 'MongoDB', jobType: 'backend' },
      { image: '/images/backend-6.png', label: 'Cassandra', jobType: 'backend' },
      { image: '/images/frontend-7.png', label: 'Sass', jobType: 'frontend' },
      { image: '/images/frontend-8.png', label: 'Material UI', jobType: 'frontend' },
    ],
  },
  {
    colums: 'third-column',
    skills: [
      { image: '/images/structure-2.png', label: 'GCP', jobType: 'infrastructure' },
      { image: '/images/structure-3.png', label: 'DigitalOcean', jobType: 'infrastructure' },
      { image: '/images/structure-4.png', label: 'AWS', jobType: 'infrastructure' },
      { image: '/images/structure-5.png', label: 'Kubernetes', jobType: 'infrastructure' },
      { image: '/images/frontend-3.png', label: 'Javascript', jobType: 'frontend' },
      { image: '/images/design-1.png', label: 'Balsamic', jobType: 'design' },
      { image: '/images/design-2.png', label: 'Invision', jobType: 'design' },
      { image: '/images/design-3.png', label: 'Figma', jobType: 'design' },
      { image: '/images/frontend-6.png', label: 'Vue.JS', jobType: 'frontend' },
      { image: '/images/design-4.png', label: 'Principle', jobType: 'design' },
      { image: '/images/design-5.png', label: 'Sketch', jobType: 'design' },
      { image: '/images/design-6.png', label: 'Adobe suite', jobType: 'design' },
      { image: '/images/design-7.png', label: 'Zeplin', jobType: 'design' },
      { image: '/images/design-8.png', label: 'Illustrator', jobType: 'design' },
      { image: '/images/design-9.png', label: 'Lottie', jobType: 'design' },
      { image: '/images/design-10.png', label: 'Photoshop', jobType: 'design' },
    ],
  },
]
