import { Manrope } from 'next/font/google'
import './globals.css'

const inter = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/favicon.png',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' class='scroll-smooth '>
      <body
        className={` ${inter.className}`}
      >
        {children}
      </body>
    </html>
  )
}
