import { Manrope } from 'next/font/google'
import './globals.css'
import Aos from 'aos'

const inter = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'Udev-clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='scroll-smooth '>
      <head>
        <link rel='shortcut icon' href='/images/favicon.png' type='image/x-icon' />
      </head>
      <body className={` ${inter.class}`}>{children}</body>
    </html>
  )
}
