import { Manrope } from 'next/font/google'
import './globals.css'
import logo from '@/public/images/favicon.png'

const inter = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: `${logo}`,
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' class='scroll-smooth '>
      <body className={` ${inter.class}`}>{children}</body>
    </html>
  )
}
